config/routes.rb
Rails.application.routes.draw do
  
  ## Customer routes
  devise_for :customers, :controllers => { :registrations => "customers/registrations", :sessions => "customers/sessions" }
  devise_scope :customer do
    get 'customer/login', to: 'devise/sessions#new'
    get 'customer/signup', to: 'devise/registrations#new'
    get 'customer/password-settings', to: 'customers/registrations#edit'
    get 'customer/retrieve-password', to: 'devise/passwords#new'
  end
  authenticated :customer do
    root 'customers#index', as: :authenticated_customer_root
  end
  get 'customers/make_reservation', to: 'customers#make_reservation'
  get '/customers/dashboard', to: 'customers#dashboard'
  get '/inbox', to: 'conversations#inbox'
  get '/bookings', to: 'customers#bookings'
  get '/reservation/:id/meals', to: 'customers#reservation_meals'
  get '/edit/profile', to: 'customers#edit'
  get '/customer/edit/profile', to: 'customers#edit'
  get '/featured-listings', to: 'customers#featured_listings'
  get '/:location/listings', to: 'meals#location_based_listings'
  get '/edit/verification', to: 'customers#edit_verification'
  get '/submit_token', to: 'customers#submit_token'
  get '/save_listing/:id', to: 'customers#save_listing'
  get '/wishlist', to: 'customers#wishlist'
  get '/message_chef/:id', to: 'customers#message_chef'
  get '/update_reservation', to: 'reservations#update_reservation'
  ## END CUSTOMER ROUTES ##
  
  ## Chef routes
  devise_for :chefs, :controllers => { :registrations => "chef/registrations" }
  devise_scope :chef do
    get 'chef/login', to: 'devise/sessions#new'
    get 'chef/signup', to: 'devise/registrations#new'
    get 'chef/password-settings', to: 'chef/registrations#edit'
    get 'chef/retrieve-password', to: 'devise/passwords#new'
  end
  authenticated :chef do
    root 'chefs#payout_form', as: :authenticated_chef_root
  end
  get '/chef_onboarding', to: 'chefs#onboarding'
  get '/chef/dashboard', to: 'chefs#dashboard'
  get '/inbox', to: 'conversations#inbox'
  get '/chef/edit/profile', to: 'chefs#edit'
  get '/reservations', to: 'chefs#reservations'
  get '/accept_reservation', to: 'chefs#accept_reservation'
  get '/deny_reservation', to: 'chefs#deny_reservation'
  get '/reservation/:id/:customer_id/accepted', to: 'chefs#accepted'
  get '/reservations/pending', to: 'chefs#pending'
  get '/reservations/accepted', to: 'chefs#all_accepted'
  get '/reservations/denied', to: 'chefs#denied'
  get '/b/:shortened_url', to: 'reservations#book'
  get '/chef/edit/social', to: 'chefs#social_form'
  get '/chef/edit/payout', to: 'chefs#payout_form'
  get '/change_payout', to: 'chefs#change_payout'
  get '/my-requests', to: 'chefs#payout_form'
  get '/chef/edit/listings', to: 'chefs#my_listings'
  get '/verify_bank', to: 'chefs#verify_bank'
  get '/chef/account-created', to: 'chefs#account_created'
  get '/load_reservations', to: 'chefs#load_reservations_category'
  get '/sort_reservations', to: 'chefs#sort_reservations'
  get '/view_request/:id', to: 'chefs#view_request'
  get '/message_diner/:id', to: 'chefs#message_diner'
  post '/rate_diner', to: 'chefs#rate_diner'
  get '/add-ingredients/:id', to: 'meals#ingredients_list', as: 'add_ingredients'
  post "/create_ingredient", to: 'meals#create_ingredient'
  get '/listing/:id/ingredients', to: 'meals#ingredients_list'
  get '/remove_ingredient', to: 'meals#remove_ingredient'
  get '/trigger_payout', to: 'chefs#trigger_payout'
  ## END CHEF ROUTES ##
  
  ## RESOURCES
  resources :conversations, except: [:delete, :edit, :update]
  resources :messages, only: :create
  resources :chefs, :reservations, :customers, :meals
  ## END RESOURCES ##
  
  ## Global routes
  get '/meal/search', to: 'main#search_page'
  get '/search', to: 'main#search'
  get '/new-dish', to: 'meals#new'
  get '/meal/:id/booking-confirmation', to: 'meals#booking_confirmation'
  get '/cook/:id', to: 'chefs#show'
  get '/cook/:username', to: 'chefs#show'
  get '/chef/:username', to: 'chefs#show'
  get '/chat/:id', to: 'conversations#show', as: 'chat'
  get '/dish/:id/:slug', to: 'meals#show', as: 'dish'
  get '/dish/:id/:slug/edit', to: 'meals#edit', as: 'edit_dish'
  get '/new/chat', to: 'conversations#create'
  get '/new/customer/chat', to: 'conversations#contact_customer'
  post '/create_message', to: 'conversations#create_message'
  get '/star/:id', to: 'conversations#star', as: "star_conversation"
  get '/archive/:id', to: 'conversations#archive', as: "archive_conversation"
  get '/unarchive/:id', to: 'conversations#unarchive', as: "unarchive_conversation"
  get '/inbox/archived', to: 'conversations#archived'
  get '/inbox/all', to: 'conversations#all'
  get 'user_type', to: 'main#user_type'
  get '/c/:username', to: 'chefs#show'
  get '/book/:username/:id', to: 'reservations#book', as: 'book'
  get '/start_reservation/:username', to: 'reservations#start_reservation'
  post '/reserve', to: 'reservations#reserve'
  post '/complete-reservation', to: 'reservations#complete_reservation'
  get '/booking-complete', to: 'reservations#booking_complete'
  get '/booking-accepted', to: 'reservations#booking_accepted'
  get '/booking/confirmation/:id', to: 'reservations#booking_confirmation'
  post '/submit_cancellation_request', to: 'reservations#cancel_reservation'
  post '/report-cook', to: 'main#report'
  post '/rate', to: 'main#rate'
  post '/rate_meal', to: 'main#rate_meal'
  get '/booking-estimate', to: 'reservations#booking_estimate'
  get '/search_meal_reviews', to: 'meals#search_meal_reviews'
  get '/browse_reviews', to: 'meals#browse_reviews'
  get '/tagged/:tag', to: 'meals#search_by_tag'
  get '/category/:category', to: 'meals#search_by_category'
  get '/filter_dishes', to: 'meals#filtered_search'
  get '/refer-a-chef', to: 'main#refer_a_chef'
  post '/submit-chef-referral', to: 'main#submit_chef_referral'
  get '/referral', to: 'main#referral'
  get '/verify_referral/:ref', to: 'main#verify_referral'
  get '/join', to: 'main#join'
  get '/new_user_guidelines', to: 'main#new_user_guidelines'
  get '/accept_guidelines', to: 'main#accept_guidelines'
  get '/terms', to: 'main#terms'
  get '/contact-us', to: "main#contact"
  ## END GLOBAL ROUTES ##
  
  
  
  root 'main#home'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    has_many :messages, dependent: :destroy
    belongs_to :chef
    belongs_to :customer
    
    def participants
        [self.chef, self.customer]
    end
    
    def self.not_archived(user)
        sender_type = user.user_type
        self.where("archived_by NOT LIKE '%#{sender_type}%'")
    end
    
    def self.archived(user)
        sender_type = user.user_type
        self.where("archived_by LIKE '%#{sender_type}%'")
    end
    
    def verify_last_accessed_by(user)
        if self.last_accessed.to_datetime < user.last_sign_in_at
            self.update(last_accessed: Time.zone.now)
        end
    end
    
    def correspondent(messager)
        return (messager.user_type == "customer" ? Chef.find_by(id: self.chef_id) : Customer.find_by(id: self.customer_id))
    end
    
    def last_message
        messages.last.created_at
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user, only: :inbox
    before_action :user
    before_action :check_participants, only: :show
    before_action :check_archives, only: [:archive, :unarchive, :inbox]
    
    def inbox
    end
    
    def archive
        @conversation = Conversation.find_by(id: params[:id])
        archiver = current_customer ? "customer" : "chef"
        @conversation.update(archived_by: @conversation.archived_by << archiver)
        render 'archive', :layout => false
    end
    
    def unarchive
        @conversation = Conversation.find_by(id: params[:id])
        archiver = current_customer ? "customer" : "chef"
        @conversation.update(archived_by: @conversation.archived_by.split(archiver).join(''))
        render 'unarchive', :layout => false
    end
    
    def archived
        @archived = @user.conversations.archived(@user).order("updated_at DESC")
        render :layout => false
    end
    
    def all
        @active = @user.conversations.not_archived(@user).order("updated_at DESC")
        render :layout => false
    end
    
    def show
        @conversation = Conversation.find_by(id: params[:id])
        @conversation.update(last_accessed: Time.zone.now, last_accessed_by_user_type: @user.user_type)
        @message = Message.new
        @messages = @conversation.messages.reverse
    end
    
    def create
        @conversation = Conversation.create(chef_id: params[:chef_id], customer_id: current_customer.id)
        redirect_to chat_path(:id => @conversation.id)
    end
    
    def contact_customer
        @conversation = Conversation.create(chef_id: current_chef.id, customer_id: params[:customer_id])
        redirect_to chat_path(:id => @conversation.id)
    end
    
    def create_message
        @message = Message.new(message_params)
        @conversation = Conversation.find_by(id: params[:conversation_id])
        @message.conversation_id = @conversation.id
        @message.sender_type == "customer" ? @message.customer_id = params["sender_id"] : @message.chef_id = params["sender_id"]
        respond_to do |format|
            if @message.save
                @messages = @conversation.messages.reverse
                format.js { render 'new_message', :layout => false }
                MessageUpdate.alert_receiver @message, @message.sender, @message.receiver
            end
        end
    end
    
    private
    
    def message_params
        params.require(:message).permit(:content, :sender_type)
    end
    
    def user
        @user = (current_customer || current_chef)
    end
    
    def check_participants
        @conversation = Conversation.find_by(id: params[:id])
        redirect_to root_path if !@conversation.participants.include? @user
    end
    
    def authenticate_user
        # current_customer ? authenticate_customer! : authenticate_chef!
        if !user
            redirect_to user_type_path
        end
    end
    
    def check_archives
        @user = user
        @active = @user.conversations.not_archived(@user).sort_by(&:last_message).reverse
        @archived = @user.conversations.archived(@user)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
    
    def message_text_alignment(type)
        if type == "chef"
            if current_chef
                "text-right"
            end
        else
            if current_customer
                "text-right"
            end
        end
    end
    
    def message_box_alignment(type)
        if type == "chef"
            if current_chef
                "float-right current-sender"
            else
                "float-left"
            end
        else
            if current_customer
                "float-right current-sender"
            else
                "float-left"
            end
        end
    end
    
    def message_sender_alignment(type, side)
        if message_box_alignment(type) == "float-right"
            if side == "left"
                "no-display"
            else
                "float-left"
            end
        elsif message_box_alignment(type) == "float-left"
            if side == "right"
                "no-display"
            else
                "float-right"
            end
        end
    end
    
    def current_sender
        if current_chef
            current_chef
        else
            current_customer
        end
    end
    
    def messagee(chef_id, customer_id)
        if current_chef
            Customer.find_by(id: customer_id)
        else
            Chef.find_by(id: chef_id)
        end
    end
    
    def new_message?(message)
        message.conversation.last_accessed_by_user_type != user.user_type && message.created_at > message.conversation.last_accessed.to_datetime
    end
    
    def message_snipet_color(message)
        if new_message? message
            ""
        else
            "text-muted"
        end
    end
    
end

app/views/conversations/_conversations.html.erb
<% if conversations.present? %>
    <% conversations.each do |c| %>
        <div class="col-lg-12 no-mobile-padding" id="conversation-block-<%= c.id %>">
            <div class="row" onmouseover="showControls(<%= c.id %>)", onmouseout="hideControls(<%= c.id %>)">
                <div class="col-md-2 text-left">
                    <div id="cook-avi" class="cursor-pointer"
                        style="height: 40px; width: 40px;
                                overflow: hidden; border-radius: 20px;
                                border: 0.5px solid #e7e7e9;"
                        id="dropdownMenuButton" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <img src="<%= messagee(c.chef_id, c.customer_id).image %>" alt="cook"
                            style="height: auto; width: inherit;">
                    </div>
                </div>
                <div class="col-md-2">
                    <p style="font-size: 14px;" ><%= messagee(c.chef_id, c.customer_id).first_name %></p>
                    <p style="font-size: 14px;"><%= c.messages.last.created_at.strftime('%b %e, %Y') %></p>
                </div>
                <div class="col-md-6" style="padding-bottom: 10px;">
                    <%= link_to chat_path(:id => c.id, :correspondent_id => messagee(c.chef_id, c.customer_id).id), class:"background-transparent no-underline #{message_snipet_color c.messages.last}", style:"width: 100%;" do %>
                        <p style="font-size: 14px;" class="bold">"<%= c.messages.last.content_snipet %>"</p>
                        <p style="font-size: 14px;"><%= messagee(c.chef_id, c.customer_id).full_address %></p>
                    <% end %>
                </div>
                <div class="col-md-2">
                    <p id="archive-<%= c.id %>">
                        <% if (current_chef || current_customer).has_archived c %>
                            <%= link_to unarchive_conversation_path(c), class:"btn btn-link theme-green", style:"padding: 0; font-size: 13px !important", remote: true do %>
                                <i class="fa fa-archive"></i> Unarchive
                            <% end %>
                        <% else %>
                            <%= link_to archive_conversation_path(c), class:"btn btn-link theme-blue control control#{c.id}", style:"display: none; padding: 0; font-size: 13px !important", remote: true do %>
                                <i class="fa fa-archive"></i> Archive
                            <% end %>
                        <% end %>
                    </p>
                </div>
            </div>
            <% if !(c == conversations.last) %><hr><% end %>
        </div>
    <% end %>
<% else %>
    <div class="col-md-12 text-center text-muted">
        <i class="fa fa-envelope-o" style="font-size: 24px;"></i>
        <p class="add-margin-top">Your inbox is empty</p>
    </div>
<% end %>

<script type="text/javascript">
    function showControls(id) {
        $('.control' + id).show();
    }
    
    function hideControls(id) {
        $('.control' + id).hide();
    }
</script>

app/views/conversations/_inbox_navs.html.erb
<button class="btn btn-primary btn-block height-50 add-margin-bottom" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span>All Messages (<%= @active.count %>)</span> <i class="fa fa-angle-down"></i>
</button>
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton"
    style="padding-top: 0; padding-bottom: 0;">
    <a class="background-transparent dropdown-item cursor-pointer"
        onclick="loadConversationCategory('all', 'conversations-box')"
        style="width: inherit;">
        All Messages (<%= @active.count %>)
    </a>
    <div class="dropdown-divider"></div>
    <a class="background-transparent dropdown-item cursor-pointer archived-conversations"
        onclick="loadConversationCategory('archived', 'conversations-box')">
        Archived (<%= @archived.count %>)
    </a>
</div>

app/views/conversations/_messages.html.erb
<style>
    .sender-avatar, .sender-message {
        display: inline-block;
    }
</style>

<% messages.each do |m| %>
    <div class="col-md-12" style="margin-top: 20px;">
        <% if m.sender != user %>
            <div class="sender-avatar float-left" style="width: 20%;">
                <div id="cook-avi" class="cursor-pointer"
                    style="height: 60px; width: 60px;
                            overflow: hidden; border-radius: 30px;
                            border: 0.5px solid #e7e7e9;"
                    id="dropdownMenuButton" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <img src="<%= m.sender.image %>" alt="cook"
                        style="height: auto; width: inherit;">
                </div>
            </div>
        <% end %>
        <% if m.sender == user %>
            <div class="sender-avatar float-right text-right" style="width: 11%; margin-left: 9%;">
                <div id="cook-avi" class="cursor-pointer"
                    style="height: 60px; width: 60px;
                            overflow: hidden; border-radius: 30px;
                            border: 0.5px solid #e7e7e9;"
                    id="dropdownMenuButton" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <img src="<%= m.sender.image %>" alt="cook"
                        style="height: auto; width: inherit;">
                </div>
            </div>
        <% end %>
        <div class="card sender-message <%= message_box_alignment(m.sender_type) %>" style="width: 80%;">
            <div class="card-body text-left">
                <p><%= m.content %></p>
                <p class="font-14 opaque message-timestamp"><%= (m.created_at - 5.hour).strftime('%b %e, %Y at %l:%M%p') %></p>
            </div>
        </div>
    </div>
<% end %>

app/views/conversations/all.js.erb
$('#conversations-box')
.html(`
    <div class="card-body">
        <div class="row">
            <%= render partial: 'conversations', locals: { conversations: @active } %>
        </div>
    </div>
`);

app/views/conversations/archive.js.erb
$('#conversation-block-<%= @conversation.id %>').fadeOut();
$('.inbox-navs')
.html(`
    <%= render 'inbox_navs' %>
`);

app/views/conversations/archived.js.erb
$('#conversations-box')
.html(`
    <div class="card-body">
        <div class="row">
            <%= render partial: 'conversations', locals: { conversations: @archived } %>
        </div>
    </div>
`);

app/views/conversations/inbox.html.erb
<section id="customer-inbox" class="col-lg-10 offset-lg-1">
    <div class="display-flex mobile-block-display">
        <div class="col-lg-3 no-padding">
            <div class="dropdown inbox-navs">
                <%= render 'inbox_navs' %>
            </div>
        </div>
    </div>
    <div class="dh-card no-mobile-padding" id="conversations-box">
        <%= render partial: 'conversations', locals: { conversations: @active } %>
    </div>
</section>

<script type="text/javascript">
    function loadConversationCategory(category, element) {
        loading(element);
        $.get('/inbox/' + category);
    }
</script>

app/views/conversations/new_message.js.erb
$('#all-messages')
.html(`
    <%= render partial: 'messages', locals: { messages: @messages } %>
`);

document.querySelector('#message-form').reset();

app/views/conversations/show.html.erb
<style>
    .row {
        margin: 0 !important;
    }
</style>

<section id="conversation">
    <% if (current_chef || current_customer).has_archived @conversation %>
        <div class="row" id="conversation-archived-label">
            <div class="col-md-12">
                <div class="alert alert-warning" role="alert">
                    This conversation is currently archived.
                    <%= link_to unarchive_conversation_path(@conversation), class:"btn btn-link bold", remote: true do %>
                        <i class="fa fa-archive"></i> Unarchive it.
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
    <div class="row">
        <div class="col-md-4 add-margin-bottom">
            <div class="card">
                <div class="card-body text-center">
                    <div id="cook-avi" class="cursor-pointer" align="center"
                        style="height: 130px; width: 130px; margin: auto;
                                overflow: hidden; border-radius: 65px;
                                border: 0.5px solid #e7e7e9;"
                        id="dropdownMenuButton" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <img src="<%= @conversation.correspondent(user).image %>" alt="cook"
                            style="height: auto; width: inherit;">
                    </div>
                    
                    <div class="add-margin-top">
                        <h5 style="font-weight: 700;">
                            <%= @conversation.correspondent(user).first_name %>
                        </h5>
                    </div>
                    
                    <div class="add-margin-top">
                        <h6>
                            <%= @conversation.correspondent(user).abridged_address %>
                        </h6>
                    </div>
                    
                    <% if current_customer %>
                        <div class="cook-rating add-margin-top" align="center">
                            <% 5.times.each_with_index do |s, idx| %>
                                <span class="star">
                                    <i class="<%= star_rating(idx + 1, @conversation.correspondent(user)) %> theme-cyan"
                                        style="font-size: 15px;"></i>
                                </span>
                            <% end %>
                            <span class="rating-count" style="font-size: 14px;">
                                <%= @conversation.correspondent(user).rating_count %>
                            </span>
                        </div>
                    <% end %>
                    
                    <div class="add-margin-top">
                        <% if current_customer %>
                            <% if current_customer.has_not_reported(@conversation.correspondent(user)) %>
                                <p class="text-center">
                                    <a class="background-transparent text-muted font-15 cursor-pointer" data-toggle="modal"
                                        data-target="#reportcook">
                                        <i class="fa fa-flag-o"></i> Report this cook
                                    </a>
                                </p>
                            <% else %>
                                <p class="text-center font-13">
                                    You have reported this cook
                                </p>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-7 offset-md-1">
            <div class="row">
                <div class="col-md-12 no-padding">
                    <form id="message-form" data-remote="true" action="/create_message" method="post">
                        <div class="card">
                            <div class="card-body" style="padding: 0;">
                                <input type="hidden" name="conversation_id" value="<%= @conversation.id %>">
                                <input type="hidden" name="message[sender_type]" value="<%= user.user_type %>">
                                <input type="hidden" name="sender_id" value="<%= user.id %>">
                                <textarea class="form-control height-100 no-box-shadow no-border background-transparent"
                                    name="message[content]" placeholder="Type a new message..."></textarea>
                            </div>
                            <div class="card-footer" align="right">
                                <button class="btn btn-secondary" data-disable-with="Sending...">
                                    Send Message <i class="fa fa-send"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            
            <% if current_customer %>
                <div style="padding: 43px 0 15px 0;" class="text-middle-hr">
                    <div style="width: 100%;">
                        <hr style="margin: 0;">
                    </div>
                    <div style="margin-top: -13px;" align="center">
                      <span style="font-size: 14px; background-color: #fff; padding: 0 10px;">
                        Reminder -
                        <a href="/c/<%= @conversation.correspondent(user).username %>"
                            class="background-transparent theme-cyan">
                            Review This cook
                        </a>
                      </span>
                    </div>
                </div>
            <% end %>
            
            <div class="row add-margin-top" id="all-messages">
                <%= render partial: 'messages', locals: { messages: @messages } %>
            </div>
        </div>
    </div>
</section>

app/views/conversations/unarchive.js.erb
$('#conversation-block-<%= @conversation.id %>').fadeOut();

$('.inbox-navs')
.html(`
    <%= render 'inbox_navs' %>
`);

$('#conversation-archived-label').html(`
    <div class="col-md-12">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            Conversation unarchived!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    </div>
`);