config/routes.rb
Rails.application.routes.draw do
  
  ## Customer routes
  devise_for :customers, :controllers => { :registrations => "customers/registrations", :sessions => "customers/sessions" }
  devise_scope :customer do
    get 'customer/login', to: 'devise/sessions#new'
    get 'customer/signup', to: 'devise/registrations#new'
    get 'customer/password-settings', to: 'customers/registrations#edit'
    get 'customer/retrieve-password', to: 'devise/passwords#new'
  end
  authenticated :customer do
    root 'customers#index', as: :authenticated_customer_root
  end
  get 'customers/make_reservation', to: 'customers#make_reservation'
  get '/customers/dashboard', to: 'customers#dashboard'
  get '/inbox', to: 'conversations#inbox'
  get '/bookings', to: 'customers#bookings'
  get '/reservation/:id/meals', to: 'customers#reservation_meals'
  get '/edit/profile', to: 'customers#edit'
  get '/customer/edit/profile', to: 'customers#edit'
  get '/featured-listings', to: 'customers#featured_listings'
  get '/:location/listings', to: 'meals#location_based_listings'
  get '/edit/verification', to: 'customers#edit_verification'
  get '/submit_token', to: 'customers#submit_token'
  get '/save_listing/:id', to: 'customers#save_listing'
  get '/wishlist', to: 'customers#wishlist'
  get '/message_chef/:id', to: 'customers#message_chef'
  get '/update_reservation', to: 'reservations#update_reservation'
  ## END CUSTOMER ROUTES ##
  
  ## Chef routes
  devise_for :chefs, :controllers => { :registrations => "chef/registrations" }
  devise_scope :chef do
    get 'chef/login', to: 'devise/sessions#new'
    get 'chef/signup', to: 'devise/registrations#new'
    get 'chef/password-settings', to: 'chef/registrations#edit'
    get 'chef/retrieve-password', to: 'devise/passwords#new'
  end
  authenticated :chef do
    root 'chefs#payout_form', as: :authenticated_chef_root
  end
  get '/chef_onboarding', to: 'chefs#onboarding'
  get '/chef/dashboard', to: 'chefs#dashboard'
  get '/inbox', to: 'conversations#inbox'
  get '/chef/edit/profile', to: 'chefs#edit'
  get '/reservations', to: 'chefs#reservations'
  get '/accept_reservation', to: 'chefs#accept_reservation'
  get '/deny_reservation', to: 'chefs#deny_reservation'
  get '/reservation/:id/:customer_id/accepted', to: 'chefs#accepted'
  get '/reservations/pending', to: 'chefs#pending'
  get '/reservations/accepted', to: 'chefs#all_accepted'
  get '/reservations/denied', to: 'chefs#denied'
  get '/b/:shortened_url', to: 'reservations#book'
  get '/chef/edit/social', to: 'chefs#social_form'
  get '/chef/edit/payout', to: 'chefs#payout_form'
  get '/change_payout', to: 'chefs#change_payout'
  get '/my-requests', to: 'chefs#payout_form'
  get '/chef/edit/listings', to: 'chefs#my_listings'
  get '/verify_bank', to: 'chefs#verify_bank'
  get '/chef/account-created', to: 'chefs#account_created'
  get '/load_reservations', to: 'chefs#load_reservations_category'
  get '/sort_reservations', to: 'chefs#sort_reservations'
  get '/view_request/:id', to: 'chefs#view_request'
  get '/message_diner/:id', to: 'chefs#message_diner'
  post '/rate_diner', to: 'chefs#rate_diner'
  get '/add-ingredients/:id', to: 'meals#ingredients_list', as: 'add_ingredients'
  post "/create_ingredient", to: 'meals#create_ingredient'
  get '/listing/:id/ingredients', to: 'meals#ingredients_list'
  get '/remove_ingredient', to: 'meals#remove_ingredient'
  get '/trigger_payout', to: 'chefs#trigger_payout'
  ## END CHEF ROUTES ##
  
  ## RESOURCES
  resources :conversations, except: [:delete, :edit, :update]
  resources :messages, only: :create
  resources :chefs, :reservations, :customers, :meals
  ## END RESOURCES ##
  
  ## Global routes
  get '/meal/search', to: 'main#search_page'
  get '/search', to: 'main#search'
  get '/new-dish', to: 'meals#new'
  get '/meal/:id/booking-confirmation', to: 'meals#booking_confirmation'
  get '/cook/:id', to: 'chefs#show'
  get '/cook/:username', to: 'chefs#show'
  get '/chef/:username', to: 'chefs#show'
  get '/chat/:id', to: 'conversations#show', as: 'chat'
  get '/dish/:id/:slug', to: 'meals#show', as: 'dish'
  get '/dish/:id/:slug/edit', to: 'meals#edit', as: 'edit_dish'
  get '/new/chat', to: 'conversations#create'
  get '/new/customer/chat', to: 'conversations#contact_customer'
  post '/create_message', to: 'conversations#create_message'
  get '/star/:id', to: 'conversations#star', as: "star_conversation"
  get '/archive/:id', to: 'conversations#archive', as: "archive_conversation"
  get '/unarchive/:id', to: 'conversations#unarchive', as: "unarchive_conversation"
  get '/inbox/archived', to: 'conversations#archived'
  get '/inbox/all', to: 'conversations#all'
  get 'user_type', to: 'main#user_type'
  get '/c/:username', to: 'chefs#show'
  get '/book/:username/:id', to: 'reservations#book', as: 'book'
  get '/start_reservation/:username', to: 'reservations#start_reservation'
  post '/reserve', to: 'reservations#reserve'
  post '/complete-reservation', to: 'reservations#complete_reservation'
  get '/booking-complete', to: 'reservations#booking_complete'
  get '/booking-accepted', to: 'reservations#booking_accepted'
  get '/booking/confirmation/:id', to: 'reservations#booking_confirmation'
  post '/submit_cancellation_request', to: 'reservations#cancel_reservation'
  post '/report-cook', to: 'main#report'
  post '/rate', to: 'main#rate'
  post '/rate_meal', to: 'main#rate_meal'
  get '/booking-estimate', to: 'reservations#booking_estimate'
  get '/search_meal_reviews', to: 'meals#search_meal_reviews'
  get '/browse_reviews', to: 'meals#browse_reviews'
  get '/tagged/:tag', to: 'meals#search_by_tag'
  get '/category/:category', to: 'meals#search_by_category'
  get '/filter_dishes', to: 'meals#filtered_search'
  get '/refer-a-chef', to: 'main#refer_a_chef'
  post '/submit-chef-referral', to: 'main#submit_chef_referral'
  get '/referral', to: 'main#referral'
  get '/verify_referral/:ref', to: 'main#verify_referral'
  get '/join', to: 'main#join'
  get '/new_user_guidelines', to: 'main#new_user_guidelines'
  get '/accept_guidelines', to: 'main#accept_guidelines'
  get '/terms', to: 'main#terms'
  get '/contact-us', to: "main#contact"
  ## END GLOBAL ROUTES ##
  
  
  
  root 'main#home'
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
         
  has_many :meals, through: :reservations
  has_many :reservations
  has_many :messages, through: :conversations
  has_many :conversations
  has_many :cook_reports
  has_many :chef_ratings
  has_many :meal_ratings
  has_many :diner_ratings
  has_many :referrals
  has_many :reservation_cancellations
  has_many :wishlists
  
  after_create :set_referral_code, :create_rating, :send_welcome_email
  
  mount_uploader :image, ImageUploader
  
  def full_name
    [first_name, last_name].join(' ')
  end
  
  def full_address(location=nil)
    address = [street_address, town, state, zipcode].join(' ')
    address = if address.strip.empty?
      location
    else
      address
    end
  end
  
  def abridged_address
    [town.capitalize, state.upcase].join(' ')
  end
  
  def has_archived(convo)
    self.conversations.include?(convo) && convo.archived_by.include?(self.user_type)
  end
  
  def has_saved meal
    wishlists.map(&:meal_id).include? meal.id
  end
  
  def can_rate meal
    reservations.map(&:meals).flatten.include?(meal) && has_not_rated_meal(meal)
  end
  
  def has_hosted cook
    cook.reservations.map(&:customer_id).include? id
  end
  
  def has_rated cook
    self.chef_ratings.map(&:chef_id).include? cook.id if cook
  end
  
  def has_not_rated cook
    has_hosted(cook) && !has_rated(cook)
  end
  
  def average_rating
    begin
      (diner_ratings.map(&:value).sum/rating_count).to_f
    rescue
      1
    end
  end
  
  def rating_count
    diner_ratings.count
  end
  
  def has_reported cook
    self.cook_reports.map(&:chef_id).include? cook.id if cook
  end
  
  def has_not_reported cook
    !has_reported cook
  end
  
  def has_rated_meal meal
    meal_ratings.map(&:meal_id).include? meal.id if meal
  end
  
  def has_not_rated_meal meal
    !has_rated_meal meal
  end
  
  def referrals
    Referral.where(code_value: referral_code)
  end
  
  def credit_amount
    referrals.unapplied.count * 5.00
  end
  
  def accept_guidelines
    update(accepted_guidelines_on: Time.zone.now)
  end
  
  private
  
  def set_referral_code
    ref = RandomToken.random(8)
    until !Customer.exists?(referral_code: ref)
      set_referral_code
    end
    self.update(referral_code: ref)
  end
  
  def create_rating
    DinerRating
    .create(value: 5, chef_id: 1, customer_id: self.id, details: "This is an automated DinnerHost bot review.")
  end
  
  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/customers/registrations_controller.rb
class Customers::RegistrationsController < Devise::RegistrationsController
    
    # include Accessible
    # skip_before_action :check_user, only: :destroy
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :phone_number, :image])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation, :current_password])
    end
    
    def after_sign_up_path_for(resource)
        new_user_guidelines_path
    end
    
    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || super
    end

end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    # resource = Customer.find_for_database_authentication(email: params[:customer][:email])
    # return invalid_login_attempt unless resource
  
    # if resource.valid_password?(params[:customer][:password])
    #   sign_in :customer, resource
    #   return render '/customers/logged_in_customer', :layout => false
    # end
    
    # invalid_login_attempt
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  
  def invalid_login_attempt
    set_flash_message(:alert, :invalid)
    render json: flash[:alert], status: 401
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :authenticate_customer!
    before_action :set_customer
    before_action :own_reservations, only: :reservation_meals
    before_action :load_featured_meals, only: [:index, :featured_listings]
    
    def edit
    end
    
    def edit_verification
    end
    
    def submit_token
        source = params[:customer][:stripe_token][:id]
        brand = params[:customer][:stripe_token][:card][:brand]
        last_4 = params[:customer][:stripe_token][:card][:last4]
        if source.nil? || source.empty?
            @notice = "Payment update failed. Please try again"
            render "common/error", :layout => false
            return
        end
        
        begin
            stripe_acct = Stripe::Customer.retrieve(current_customer.stripe_token)
            stripe_acct.sources.last.delete
            stripe_acct.sources.create(source: source)
        rescue
            description = "Customer: #{current_customer.full_name}. ID: #{current_customer.id}"
            stripe_acct = Stripe::Customer.create(:description => description, :source => source)
        end
        
        current_customer.update(stripe_token: stripe_acct.id, has_stripe_account: true, stripe_last_4: last_4, card_brand: brand)
        
        @notice = "Payment updated!"
        render 'token_submitted', :layout => false
    end
    
    def index
        @chefs = Chef
        .near(current_customer
        .full_address("#{request.location.city}, #{request.location.state}"), 15)
        .live
    end
    
    def featured_listings
    end
    
    def save_listing
        @meal = Meal.find_by(id: params[:id])
        return if @meal.nil? or current_customer.has_saved(@meal)
        Wishlist.create(customer_id: current_customer.id, meal_id: @meal.id)
        render "listing_saved", :layout => false
    end
    
    def wishlist
        @saved = current_customer.wishlists.map(&:meal)
    end
    
    def update
        @customer.update(customer_params)
        respond_to do |format|
            if @customer.save
                if request.xhr?
                    @notice = "Profile updated!"
                    format.js { render :layout => false }
                else
                    format.html { redirect_to :back, notice: "Your profile has been updated!" }
                end
            else
                render :edit, notice: "Unable to update profile. Please try again"
            end
        end
    end
    
    def bookings
        @bookings = current_customer.reservations.active.order("created_at DESC")
    end
    
    def reservation_meals
        @meals = @reservation.meals
    end
    
    def message_chef
        @chef = Chef.find_by(id: params[:id])
        
        @conversation = Conversation.find_by(chef_id: @chef.id, customer_id: current_customer.id)
        if @conversation.nil?
          @conversation = Conversation.create(chef_id: @chef.id, customer_id: current_customer.id)
        end
        redirect_to chat_path(:id => @conversation.id)
    end
    
    private
    
    def set_customer
        @customer = current_customer
    end
    
    def own_reservations
        @reservation = Reservation.find_by(id: params[:id])
        redirect_to root_path if !(current_customer.reservations.include? @reservation)
    end
    
    def customer_params
        params
        .require(:customer)
        .permit(:first_name, :last_name, :phone_number, :twitter, :facebook, :instagram,
            :bio, :street_address, :town, :state, :zipcode, :image, :stripe_token)
    end
    
    def load_featured_meals
        @meals = Meal
        .filter_by_customer_location(current_customer
        .full_address("#{request.location.city}, #{request.location.state}"))
        .not_deleted
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_allergies.html.erb
<% if allergies %>
    <% allergies.split(',').each do |a| %>
        <span class="badge badge-primary" style="margin-left: 3px; margin-bottom: 3px;"><%= a %></span>
    <% end %>
<% else %>
    None
<% end %>

app/views/customers/_payment_form.html.erb
<form method="get" id="payment-form">
    <div class="form-row row">
        <div class="col-md-12">
            <div id="card-element" class="col-md-12"></div>
        </div>
        <div id="card-errors" role="alert" class="col-md-12"></div>
    </div>
    <div class="row">
        <div class="col-md-12 add-margin-top" align="right">
            <button class="btn btn-primary height-50 payment-form">
                Update Payment
            </button>
        </div>
    </div>
</form>

app/views/customers/_rated.html.erb
<% 5.times.each_with_index do |s, idx| %>
    <span class="star cursor-pointer unrated-star" id="star-<%= idx + 1 %>"
        onclick="showStars(this)">
        <i class="fa fa-star-o theme-cyan"
            style="font-size: 28px;"></i>
    </span>
<% end %>

<span class="rating-count" style="font-size: 18px;">
    (<%= @customer.rating_count %>)
</span>

app/views/customers/_reservation_details.html.erb
<p>
    <span class="bold">Meals</span>:
    <span class="theme-cyan">
        <%= reservation.meal_ids.split(',').length %>
    </span>
    <span class="text-muted">
        (<%= reservation.meals.map(&:name).join(", ") %>)
    </span>
</p>

<p style="margin-top: 20px;">
    <span class="bold">Booked</span> for:
    <span class="theme-cyan">
        <%= reservation.request_date.to_datetime.strftime("%b %e at ") + reservation.request_time %>
    </span>
</p>

<p style="margin-top: 20px;">
    <span class="bold">People</span>: <span class="theme-cyan"><%= reservation.people_count %></span>
    <span class="text-muted">
        (<%= (reservation.adult_count.to_s + " adults") if reservation.adult_count > 0 %>
        <%= (", " + reservation.children_count.to_s + " children") if reservation.children_count > 0 %>)
    </span>
</p>

<p style="margin-top: 20px;">
    <span class="bold">Allergies</span>: <%= render partial: 'customers/allergies', locals: { allergies: reservation.allergens } %>
</p>

app/views/customers/_reservation_refund.html.erb
<% if b.last_minute_cancellation %>
    <hr>
    
    <div style="margin-top: 5px;">
        <p>
            You are cancelling within less than 12 hours of the
            reservation time. You can only receive 25% of
            the total reservation cost.
        </p>
    </div>
<% elsif b.very_late_cancellation %>
    <hr>
    
    <div style="margin-top: 5px;">
        <p>
            You are cancelling within less than 24 hours of the
            reservation time. You can only receive 50% of
            the total reservation cost.
        </p>
    </div>
<% elsif b.late_cancellation %>
    <hr>
    
    <div style="margin-top: 5px;">
        <p>
            You are cancelling within less than 48 hours of the
            reservation time. You can only receive 75% of
            the total reservation cost.
        </p>
    </div>
<% end %>

app/views/customers/_verification_form.html.erb
<%= form_for(@customer, :html => { :multipart => true, :class => 'cook-form', :id => "cook_form", :remote => true }) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
        <h2>This post could not be saved due to the following <%= pluralize(@customer.errors.count, "error") %>:</h2>

        <ul>
            <% @customer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  
  <div class="field row">
    <div class="col-md-2">
      <label>Facebook link</label>
    </div>
    <div class="col-md-10">
      <%= f.text_field :facebook, class:"form-control no-box-shadow height-50 font-15 pf", autofocus: true, placeholder:"Facebook profile url" %>
    </div>
  </div>
  
  <div class="field row">
    <div class="col-md-2">
      <label>Instagram username</label>
    </div>
    <div class="col-md-10">
      <%= f.text_field :instagram, class:"form-control no-box-shadow height-50 font-15 pf", autofocus: true, placeholder:"Instagram username" %>
    </div>
  </div>
  
  <div class="field row">
    <div class="col-md-2">
      <label>Twitter username</label>
    </div>
    <div class="col-md-10">
      <%= f.text_field :twitter, class:"form-control no-box-shadow height-50 font-15 pf", autofocus: true, placeholder:"Twitter username" %>
    </div>
  </div>
  <%= f.hidden_field :government_id, value: "", id: "government-id" %>
  
  <div class="actions text-right action-button">
    <%= f.submit "Update", class:"btn btn-primary height-50", id:"update-profile", data: { "disable-with": "Updating..." } %>
  </div>
<% end %>

app/views/customers/bookings.html.erb
<section id="past-reservations">
    <div class="display-flex mobile-block-display">
        <div class="col-lg-12">
            <h2>Past reservations</h2>
        </div>
    </div>
    <div class="display-flex mobile-block-display" style="flex-wrap: wrap;">
        <%= render partial: 'bookings', locals: { bookings: @bookings } %>
    </div>
</section>

app/views/customers/edit.html.erb
<div class="display-flex mobile-block-display" style="flex-wrap: wrap;">
    <div class="col-lg-8 offset-lg-2 no-padding">
        <div class="dh-card">
            <h5>
                Account Details
            </h5>
            <hr>
            <%= render 'edit_profile_form' %>
        </div>
    </div>
   
    <div class="col-lg-8 offset-lg-2 no-padding" style="margin-top: 20px;">
        <div class="dh-card" id="payment-card">
            <h5>
                Add a payment method
            </h5>
            <%= render 'payment' %>
            
            <hr>
            
            <div class="add-margin-top">
                Payment processing services on DinnerHost are provided
                by
                <a class="background-transparent" href="https://stripe.com" target="_blank">
                    Stripe
                </a>
                and are subject to the 
                <a href="https://stripe.com/us/connect-account/legal" class="background-transparent" target="_blank">
                    Stripe Connected Account Agreement
                </a>
                , which includes the
                <a href="https://stripe.com/legal" class="background-transparent" target="_blank">
                    Stripe Terms of Service
                </a>
                (collectively, the “Stripe Services Agreement”).
                By agreeing to these terms or continuing to operate as a
                store on DinnerHost, you agree to be bound by the Stripe Services
                Agreement, as the same may be modified by Stripe from time to time.
                As a condition of DinnerHost enabling payment processing
                services through Stripe, you agree to provide DinnerHost accurate
                and complete information about you and your business, and
                you authorize DinnerHost to share it and transaction information
                related to your use of the payment processing services
                provided by Stripe. 
                <hr style="margin-top: 15px; margin-bottom: 15px;">
                By submitting this form, you agree to DinnerHost's
                <a class="background-transparent" href="https://app.termly.io/document/privacy-policy/613ee504-9fd4-475c-8339-ffc94ae03f72" target="_blank">terms of service</a>
                as well as Stripe's
                <a href="https://stripe.com/terms" class="background-transparent" target="_blank">terms of service</a>.
            </div>
        </div>
    </div>
</div>

<script>
    
    var stripe = Stripe("<%= stripe_key %>");
    var elements = stripe.elements();
    
    var style = {
      base: {
        color: '#32325d',
        lineHeight: '18px',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
          color: '#aab7c4'
        }
      },
      invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
      }
    };
    
    var card = elements.create('card', {style: style});
    card.mount('#card-element');
    
    card.addEventListener('change', function(event) {
      var displayError = document.getElementById('card-errors');
      if (event.error) {
        displayError.textContent = event.error.message;
      } else {
        displayError.textContent = '';
      }
    });
    
    $('.StripeElement').css('border', '1px solid #b4b4b4 !important');
    
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
        event.preventDefault();
        
        $('.payment-form')
        .prop('disabled', 'true')
        .html('Updating...');
        stripe.createToken(card).then(function(result) {
            if (result.error) {
              var errorElement = document.getElementById('card-errors');
              errorElement.textContent = result.error.message;
            } else {
                var customer = {
                    stripe_token: result.token
                };
                $.get('/submit_token', { customer: customer });
            }
        });
    });
    
</script>

app/views/customers/edit_verification.html.erb
<div class="row" style="margin: 0;">
    <div class="col-lg-8 offset-lg-2 no-padding">
        <div class="dh-card">
            <h5>
                Social Accounts
            </h5>
            <hr>
            <%=  render "verification_form" %>
        </div>
    </div>
</div>

app/views/customers/listing_saved.js.erb
$(".save-listing").html(`
    <button class="btn btn-primary" disabled>
        <i class="fa fa-heart"></i> Listing saved
    </button>
`);

app/views/customers/make_reservation.html.erb
<!--<section id="make-a-reservation">-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-md-8">-->
<!--                <div class="card">-->
<!--                    <div class="card-body">-->
<!--                        <h5><%= @meal.name %></h5>-->
<!--                        <hr>-->
<!--                        <p><%= @meal.description %></p>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-md-4">-->
<!--                <div class="card">-->
<!--                    <div class="card-body">-->
<!--                        Payment-->
<!--                        <form method="get" id="payment-form" data-disable-with="Processing request...">-->
<!--                            <div class="form-row row">-->
<!--                                <div class="col-md-12">-->
<!--                                    <div id="card-element" class="col-md-12"></div>-->
<!--                                </div>-->
<!--                                <div id="card-errors" role="alert" class="col-md-12"></div>-->
<!--                            </div>-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-12 complete-order add-margin-top">-->
<!--                                    <button class="btn btn-primary btn-block height-50 white submit-btn" id="booking-btn">-->
<!--                                        Book this cook-->
<!--                                    </button>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </form>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</section>-->

<!--<script type="text/javascript">-->
<!--    var stripe = Stripe("pk_test_4rlj7z7bgOSQVv1TrZAMhrJi");-->
    
    // Create an instance of Elements
<!--    var elements = stripe.elements();-->
    
    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
<!--    var style = {-->
<!--      base: {-->
<!--        color: '#32325d',-->
<!--        lineHeight: '18px',-->
<!--        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',-->
<!--        fontSmoothing: 'antialiased',-->
<!--        fontSize: '16px',-->
<!--        '::placeholder': {-->
<!--          color: '#aab7c4'-->
<!--        }-->
<!--      },-->
<!--      invalid: {-->
<!--        color: '#fa755a',-->
<!--        iconColor: '#fa755a'-->
<!--      }-->
<!--    };-->
    
    // Create an instance of the card Element
<!--    var card = elements.create('card', {style: style});-->
    
    // Add an instance of the card Element into the `card-element` <div>
<!--    card.mount('#card-element');-->
    
    // Handle real-time validation errors from the card Element.
<!--    card.addEventListener('change', function(event) {-->
<!--      var displayError = document.getElementById('card-errors');-->
<!--      if (event.error) {-->
<!--        displayError.textContent = event.error.message;-->
<!--      } else {-->
<!--        displayError.textContent = '';-->
<!--      }-->
<!--    });-->
    
<!--    $('.StripeElement').css('border', '1px solid #b4b4b4 !important');-->
    
    // Handle form submission //
<!--    var form = document.getElementById('payment-form');-->
<!--    form.addEventListener('submit', function(event) {-->
<!--        event.preventDefault();-->
<!--        $('#booking-btn').prop('disabled', true)-->
<!--        stripe.createToken(card).then(function(result) {-->
<!--            if (result.error) {-->
<!--              var errorElement = document.getElementById('card-errors');-->
<!--              errorElement.textContent = result.error.message;-->
<!--            } else {-->
<!--              submitOrder(result.token);-->
<!--            }-->
<!--        });-->
<!--    });-->
    
<!--    function submitOrder(token) {-->
<!--        var data = {-->
<!--            "meal_id": "<%= params[:id] %>",-->
<!--            "card_token": token-->
<!--        };-->
<!--        $.post('/reserve', { data: data });-->
<!--    }-->
    
<!--</script>-->

app/views/customers/token_submitted.js.erb
$('#payment-card').html(`<%= render 'payment' %>`);

$('#booking-btn-div').html(`
    <form action="/reserve" method="post" data-remote="true">
        <input type="hidden" value="" id="request-date" name="reservation[request_date]">
        <input type="hidden" value="" id="adult-count" name="reservation[adult_count]">
        <input type="hidden" value="" id="children-count" name="reservation[children_count]">
        <input type="hidden" value="" id="meal-ids" name="reservation[meal_ids]">
        <input type="hidden" value="" id="customer-allergies" name="reservation[allergies]">
        <button class="btn btn-primary btn-block height-50 white" disabled
                id="booking-btn" data-disable-with="Booking...">
            Book
        </button>
    </form>
`);

showNotice("<%= @notice %>");

app/views/customers/unable_to_book.js.erb
toastr
.warning("We are unable to process your request at this time. Please try again
later.");

app/views/customers/update.js.erb
showNotice("<%= @notice %>");