config/routes.rb
Rails.application.routes.draw do
  
  ## Customer routes
  devise_for :customers, :controllers => { :registrations => "customers/registrations", :sessions => "customers/sessions" }
  devise_scope :customer do
    get 'customer/login', to: 'devise/sessions#new'
    get 'customer/signup', to: 'devise/registrations#new'
    get 'customer/password-settings', to: 'customers/registrations#edit'
    get 'customer/retrieve-password', to: 'devise/passwords#new'
  end
  authenticated :customer do
    root 'customers#index', as: :authenticated_customer_root
  end
  get 'customers/make_reservation', to: 'customers#make_reservation'
  get '/customers/dashboard', to: 'customers#dashboard'
  get '/inbox', to: 'conversations#inbox'
  get '/bookings', to: 'customers#bookings'
  get '/reservation/:id/meals', to: 'customers#reservation_meals'
  get '/edit/profile', to: 'customers#edit'
  get '/customer/edit/profile', to: 'customers#edit'
  get '/featured-listings', to: 'customers#featured_listings'
  get '/:location/listings', to: 'meals#location_based_listings'
  get '/edit/verification', to: 'customers#edit_verification'
  get '/submit_token', to: 'customers#submit_token'
  get '/save_listing/:id', to: 'customers#save_listing'
  get '/wishlist', to: 'customers#wishlist'
  get '/message_chef/:id', to: 'customers#message_chef'
  get '/update_reservation', to: 'reservations#update_reservation'
  ## END CUSTOMER ROUTES ##
  
  ## Chef routes
  devise_for :chefs, :controllers => { :registrations => "chef/registrations" }
  devise_scope :chef do
    get 'chef/login', to: 'devise/sessions#new'
    get 'chef/signup', to: 'devise/registrations#new'
    get 'chef/password-settings', to: 'chef/registrations#edit'
    get 'chef/retrieve-password', to: 'devise/passwords#new'
  end
  authenticated :chef do
    root 'chefs#payout_form', as: :authenticated_chef_root
  end
  get '/chef_onboarding', to: 'chefs#onboarding'
  get '/chef/dashboard', to: 'chefs#dashboard'
  get '/inbox', to: 'conversations#inbox'
  get '/chef/edit/profile', to: 'chefs#edit'
  get '/reservations', to: 'chefs#reservations'
  get '/accept_reservation', to: 'chefs#accept_reservation'
  get '/deny_reservation', to: 'chefs#deny_reservation'
  get '/reservation/:id/:customer_id/accepted', to: 'chefs#accepted'
  get '/reservations/pending', to: 'chefs#pending'
  get '/reservations/accepted', to: 'chefs#all_accepted'
  get '/reservations/denied', to: 'chefs#denied'
  get '/b/:shortened_url', to: 'reservations#book'
  get '/chef/edit/social', to: 'chefs#social_form'
  get '/chef/edit/payout', to: 'chefs#payout_form'
  get '/change_payout', to: 'chefs#change_payout'
  get '/my-requests', to: 'chefs#payout_form'
  get '/chef/edit/listings', to: 'chefs#my_listings'
  get '/verify_bank', to: 'chefs#verify_bank'
  get '/chef/account-created', to: 'chefs#account_created'
  get '/load_reservations', to: 'chefs#load_reservations_category'
  get '/sort_reservations', to: 'chefs#sort_reservations'
  get '/view_request/:id', to: 'chefs#view_request'
  get '/message_diner/:id', to: 'chefs#message_diner'
  post '/rate_diner', to: 'chefs#rate_diner'
  get '/add-ingredients/:id', to: 'meals#ingredients_list', as: 'add_ingredients'
  post "/create_ingredient", to: 'meals#create_ingredient'
  get '/listing/:id/ingredients', to: 'meals#ingredients_list'
  get '/remove_ingredient', to: 'meals#remove_ingredient'
  get '/trigger_payout', to: 'chefs#trigger_payout'
  ## END CHEF ROUTES ##
  
  ## RESOURCES
  resources :conversations, except: [:delete, :edit, :update]
  resources :messages, only: :create
  resources :chefs, :reservations, :customers, :meals
  ## END RESOURCES ##
  
  ## Global routes
  get '/meal/search', to: 'main#search_page'
  get '/search', to: 'main#search'
  get '/new-dish', to: 'meals#new'
  get '/meal/:id/booking-confirmation', to: 'meals#booking_confirmation'
  get '/cook/:id', to: 'chefs#show'
  get '/cook/:username', to: 'chefs#show'
  get '/chef/:username', to: 'chefs#show'
  get '/chat/:id', to: 'conversations#show', as: 'chat'
  get '/dish/:id/:slug', to: 'meals#show', as: 'dish'
  get '/dish/:id/:slug/edit', to: 'meals#edit', as: 'edit_dish'
  get '/new/chat', to: 'conversations#create'
  get '/new/customer/chat', to: 'conversations#contact_customer'
  post '/create_message', to: 'conversations#create_message'
  get '/star/:id', to: 'conversations#star', as: "star_conversation"
  get '/archive/:id', to: 'conversations#archive', as: "archive_conversation"
  get '/unarchive/:id', to: 'conversations#unarchive', as: "unarchive_conversation"
  get '/inbox/archived', to: 'conversations#archived'
  get '/inbox/all', to: 'conversations#all'
  get 'user_type', to: 'main#user_type'
  get '/c/:username', to: 'chefs#show'
  get '/book/:username/:id', to: 'reservations#book', as: 'book'
  get '/start_reservation/:username', to: 'reservations#start_reservation'
  post '/reserve', to: 'reservations#reserve'
  post '/complete-reservation', to: 'reservations#complete_reservation'
  get '/booking-complete', to: 'reservations#booking_complete'
  get '/booking-accepted', to: 'reservations#booking_accepted'
  get '/booking/confirmation/:id', to: 'reservations#booking_confirmation'
  post '/submit_cancellation_request', to: 'reservations#cancel_reservation'
  post '/report-cook', to: 'main#report'
  post '/rate', to: 'main#rate'
  post '/rate_meal', to: 'main#rate_meal'
  get '/booking-estimate', to: 'reservations#booking_estimate'
  get '/search_meal_reviews', to: 'meals#search_meal_reviews'
  get '/browse_reviews', to: 'meals#browse_reviews'
  get '/tagged/:tag', to: 'meals#search_by_tag'
  get '/category/:category', to: 'meals#search_by_category'
  get '/filter_dishes', to: 'meals#filtered_search'
  get '/refer-a-chef', to: 'main#refer_a_chef'
  post '/submit-chef-referral', to: 'main#submit_chef_referral'
  get '/referral', to: 'main#referral'
  get '/verify_referral/:ref', to: 'main#verify_referral'
  get '/join', to: 'main#join'
  get '/new_user_guidelines', to: 'main#new_user_guidelines'
  get '/accept_guidelines', to: 'main#accept_guidelines'
  get '/terms', to: 'main#terms'
  get '/contact-us', to: "main#contact"
  ## END GLOBAL ROUTES ##
  
  
  
  root 'main#home'
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_chef!, only: [:create, :create_ingredient, :ingredients_list, :update, :edit, :destroy]
  before_action :own_meal, only: [:edit, :update, :destroy, :ingredients_list]
  before_action :authenticate_customer!, only: [:reserve, :booking_confirmation]
  before_action :set_meal, only: [:update, :show, :edit, :destroy]
  before_action :set_meal_attributes, only: :new
  
  def create
    @meal = Meal.new(meal_params)
    @meal.chef = current_chef
    respond_to do |format|
      if @meal.save
        format.html { redirect_to add_ingredients_path(:id => @meal.id) }
      else
        render :new
      end
    end
  end
  
  def create_ingredient
    @ingredient = Ingredient.new(ingredient_params)
    @meal = Meal.find_by(id: params[:ingredient][:meal_id])
    own_meal @meal.id
    
    @ingredient.meal = @meal
    @ingredient.chef = current_chef
    respond_to do |format|
      if @ingredient.save
        @ingredients = @meal.ingredients
        format.js { render "ingredient_added", :layout => false }
      else
        format.js { render "common/error", :layout => false }
      end
    end
  end
  
  def remove_ingredient
    @ingredient = Ingredient.find_by(id: params[:id])
    @meal = Meal.find_by(:id => params[:meal_id])
    own_meal @meal.id
    
    return warn if not_proper_user @ingredient
    @ingredient.destroy
    
    @ingredients = @meal.ingredients
    render "ingredient_removed", :layout => false
  end
  
  def ingredients_list
    @meal = Meal.find_by(id: params[:id])
    @ingredient = Ingredient.new
  end
  
  def update
    @meal.update(meal_params)
    @meal.street_address = current_chef.street_address
    @meal.town = current_chef.town
    @meal.state = current_chef.state
    @meal.zipcode = current_chef.zipcode
    respond_to do |format|
      if @meal.save
        @notice = "Listing updated!"
        format.js { render "common/show_notice", :layout => false }
      else
        render :edit
      end
    end
  end

  def show
    @cook = Chef.find_by(id: @meal.chef_id)
    @reviews = @meal.meal_ratings.reverse
  end
  
  def search_meal_reviews
    @meal = Meal.not_deleted.find(params[:meal_id])
    @reviews = @meal.meal_ratings.search(params[:search])
    render :layout => false
  end
  
  def browse_reviews
    page = params[:page]
    @meal = Meal.not_deleted.find(params[:meal_id])
    @all_reviews = @meal.meal_ratings.reverse
    if page.present?
      @page = page.to_i
      if @page > 1
        idx = @page - 2
        @page_start = (@page * 2) + 1 + (3*idx)
        @page_end = @page_start + 4
        @reviews = @meal.meal_ratings.reverse[@page_start..@page_end]
      elsif page.to_i == 1
        @reviews = @meal.meal_ratings.reverse[0..4]
      end
    else
      @reviews = @meal.meal_ratings.reverse[0..4]
    end
    render :layout => false
  end
  
  def search_by_tag
    @meals = Meal.search(params[:tag])
  end
  
  def search_by_category
    @meals = Meal.not_deleted.filter_type(params[:category])
  end
  
  def filtered_search
    data = params["data"]
    @meal_type = data["meal_type"]
    @request_location = data["request_location"]
    @filter_data = JSON.parse(data["filters"]) if data["filters"]
    
    filtered_by_type_and_location = Meal.not_deleted.filter_type(@meal_type).near(@request_location, 20)
    @meals = Meal.process_filters(@filter_data, filtered_by_type_and_location)
    render :layout => false
  end
  
  def location_based_listings
    @meals = Meal.not_deleted.near(params[:location], 15)
  end
  
  def reserve
    @reservation = Reservation.new(reservation_params)
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to "/booking/confirmation/#{@reservation.id}" }
      end
    end
  end
  
  def book
    begin
      @meal = Meal.not_deleted.find_by(id: params[:data][:meal_id])
      @reservation = Reservation.book_chef(@meal, params[:data][:card_token][:id], current_customer)
    rescue
      render 'unable_to_book', :layout => false
      return
    end
  end
  
  def booking_confirmation
    @reservation = Reservation.find_by(id: params[:id])
  end
  
  def report_meal
    @report = MealReport.new(meal_report_params)
    respond_to do |params|
      if @report.save
        format.js { render 'report_sent', :layout => false }
      end
    end
  end

  def edit
  end
  
  def destroy
    @meal.update(deleted: true)
    redirect_to "/chef/edit/listings", notice: "Listing successfully removed!"
  end
  
  private
  
  def set_meal(id=nil)
    @meal = Meal.not_deleted.find(id || params[:id])
  end
  
  def own_meal(id=nil)
    set_meal id
    @notice = "Unauthorized access!"
    
    if @meal.chef != current_chef
      if request.xhr?
        render "common/unauthorized", :layout => false
      else
        redirect_to :back, notice: @notice
      end
    end
  end
  
  def set_meal_attributes
    @meal = Meal.new
    @meal.street_address = current_chef.street_address
    @meal.town = current_chef.town
    @meal.state = current_chef.state
    @meal.zipcode = current_chef.zipcode
  end
  
  def meal_params
    params
    .require(:meal)
    .permit(:name, :description, :street_address, :town, :state,
            :zipcode, :image, :dish_order, :serving_temperature,
            :allergens, :tags, :meal_type, :prep_fee, :course, :flavor,
            :notable_ingredients)
  end
  
  def ingredient_params
    params.require(:ingredient).permit(:name, :quantity, :additional_details)
  end
  
  def meal_report_params
    params.require(:meal_report).permit(:report_type, :details, :meal_id, :customer_id)
  end
  
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :adult_count, :children_count)
  end
  
  def current_user
    current_chef || current_customer
  end
  
  def not_proper_user(obj)
    obj.user != current_user
  end
  
  def warn
    @notice = "Unauthorized Access!"
    render "common/unauthorized", :layout => false
  end
end

app/helpers/meals_helper.rb
require './lib/recommendation.rb'

module MealsHelper
    
    include Recommendation
    
    def booking_controls
        current_chef ? 'cook_controls' : 'customer_controls'
    end
    
    def meal_report_categories
        ["This is not a real cook", "This cook has fradulent listings", "This cook has offensive listings", "It's something else"]
    end
    
    def meal_report_header(step, text=nil)
        case step.downcase
        when 'intro'
            "Why are you reporting this meal?"
        else
            case text.downcase
            when "it's a scam"
                "Why do you believe this meal is a scam?"
            when "it's innacurate"
                "What makes this meal innacurate?"
            when "it's offensive"
                "What makes this meal offensive?"
            else
                "Please provide more details for your report"
            end
        end
    end
    
    def social_share_text(listing, social="dinnerhost")
        "This looks so good! '#{listing.name}' @#{social}"
    end
    
    def recommended_dishes(dish)
        meals = Meal.where.not(id: dish.id)
        like = []
        
        dish.tags.split(",").map {|d| d.strip }.each do |t|
            like << meals.matches("tags", t)
        end
        return like.flatten.uniq.first(3) if !like.empty?
        
        fallback = Meal.where.not(id: dish.id).where(meal_type: dish.meal_type).first(3)
        return fallback if !fallback.empty?
        
        further_fallback = Meal.where.not(id: dish.id).first(3)
        return further_fallback
    end
end

app/views/meals/_cook_controls.html.erb
<%= link_to edit_meal_path(@meal), class:"btn btn-info" do %>
    Edit event <i class="fa fa-pencil"></i>
<% end %>

<%= link_to meal_path(@meal), class:"btn btn-danger", method: :delete do %>
    Delete event <i class="fa fa-times-circle-o"></i>
<% end %>

app/views/meals/_customer_controls.html.erb
<%= link_to customers_make_reservation_path(:id => @meal.id), class:"btn btn-success" do %>
    Make reservation <i class="fa fa-long-arrow-right"></i>
<% end %>

app/views/meals/_form.html.erb
<%= form_for(@meal, :html => { :multipart => true, :class => 'meal-form', :id => "meal_form" }, :remote => true) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
        <h2>This post could not be saved due to the following <%= pluralize(@meal.errors.count, "error") %>:</h2>

        <ul>
            <% @meal.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <span id="meal-id" class="no-display"><%= @meal.id %></span>
  <div class="field row">
    <div class="col-md-2">
      <label>Dish name</label>
    </div>
    <div class="col-md-10">
      <%= f.text_field :name, class:"form-control no-box-shadow height-50 font-15 pf", label: false, placeholder: "Provide a short but descriptive name for this dish", required: true %>
    </div>
  </div>
  
  <div class="field row">
    <div class="col-md-2">
      <label>Dish description<br /><span class="text-muted">(Max: 100 words)</span></label>
    </div>
    <div class="col-md-10">
      <%= f.text_area :description, class:"form-control no-box-shadow font-15 pf", style: "height: 200px !important;", label: false, placeholder: "Provide a brief description for this dish", required: true %>
    </div>
  </div>
  
  <hr>
  
  <div class="field row">
    <div class="col-md-4 add-margin-bottom-mobile">
      <%= f.text_field :meal_type, class:"form-control no-box-shadow height-50 font-15 pf", label: false, placeholder: "Cuisine (Ex: Korean)", required: true %>
    </div>
    
    <div class="col-md-3 add-margin-bottom-mobile" style="width: 100%;">
      <div class="dropdown">
        <div style="border: 0.5px solid #e7e7e9; border-radius: 2px;"
          id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false" class="cursor-pointer">
          <div class="row">
            <div class="col-md-12" style="padding: 15px;">
              <p class="font-15 text-left" style="padding: 0 15px;">
                <span class="float-left" id='course-value'>
                  <%= @meal.course.present? ? @meal.course : "choose course" %>
                </span>
                <span class="float-right">
                  <i class="fa fa-angle-down"></i>
                </span>
              </p>
            </div>
          </div>
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"
          style="padding-top: 0; padding-bottom: 0;">
          <a class="dropdown-item cursor-pointer"
            onclick="changeCourse('appetizer');">
            Appetizer
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item cursor-pointer"
            onclick="changeCourse('Entree');">
            Entree
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item cursor-pointer"
            onclick="changeCourse('Dessert');">
            Dessert
          </a>
        </div>
      </div>
      <%= f.text_field :course, class:"no-display", id: "course", label: false, value:"" %>
    </div>
    
    <div class="col-md-2 add-margin-bottom-mobile" style="width: 100%;">
      <div class="dropdown">
        <div style="border: 0.5px solid #e7e7e9; border-radius: 2px;"
          id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false" class="cursor-pointer">
          <div class="row">
            <div class="col-md-12" style="padding: 15px;">
              <p class="font-15 text-left" style="padding: 0 15px;">
                <span class="float-left" id='served'>
                  <%= @meal.serving_temperature.present? ? "served " + @meal.serving_temperature : "served hot" %>
                </span>
                <span class="float-right">
                  <i class="fa fa-angle-down"></i>
                </span>
              </p>
            </div>
          </div>
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"
          style="padding-top: 0; padding-bottom: 0;">
          <a class="dropdown-item cursor-pointer"
            onclick="changeTemp('hot');">
            Hot
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item cursor-pointer"
            onclick="changeTemp('cold');">
            Cold
          </a>
        </div>
      </div>
      <%= f.text_field :serving_temperature, class:"form-control no-box-shadow height-50 font-15 pf no-display", id: "serving-temp", label: false, value:"hot", required: true %>
    </div>
    
    <div class="col-md-3 add-margin-bottom-mobile" style="width: 100%;">
      <div class="dropdown">
        <div style="border: 0.5px solid #e7e7e9; border-radius: 2px;"
          id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false" class="cursor-pointer">
          <div class="row">
            <div class="col-md-12" style="padding: 15px;">
              <p class="font-15 text-left" style="padding: 0 15px;">
                <span class="float-left" id='flavor-value'>
                  <%= @meal.flavor.present? ? @meal.flavor : "choose flavor" %>
                </span>
                <span class="float-right">
                  <i class="fa fa-angle-down"></i>
                </span>
              </p>
            </div>
          </div>
        </div>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"
          style="padding-top: 0; padding-bottom: 0;">
          <a class="dropdown-item cursor-pointer"
            onclick="changeFlavor('Nonspicy');">
            Nonspicy
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item cursor-pointer"
            onclick="changeFlavor('Mild');">
            Mild
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item cursor-pointer"
            onclick="changeFlavor('Spicy');">
            Spicy
          </a>
        </div>
      </div>
      <%= f.text_field :flavor, class:"no-display", id: "flavor", label: false, value:"" %>
    </div>
  </div>
  
  <hr>
  
  <div class="field row">
    <div class="col-md-2">
      <label>Allergens</label>
    </div>
    <div class="col-md-10">
      <%= f.text_field :allergens, class:"form-control no-box-shadow height-50 font-15 pf", label: false, placeholder: "Comma separated (Ex: peanuts, soya, shellfish, dairy...)", required: true %>
    </div>
  </div>
  
  <div class="field row">
    <div class="col-md-2">
      <label>Add tags</label>
    </div>
    <div class="col-md-10">
      <%= f.text_field :tags, class:"form-control no-box-shadow height-50 font-15 pf", label: false, placeholder: "Comma separated (Ex: chicken, paprika, portabello mushroom...)", required: true %>
    </div>
  </div>
  
  <div class="field row">
    <div class="col-md-2">
      <label>Add an image</label>
    </div>
    <div class="col-md-10">
      <div class="card cursor-pointer meal-image-card">
        <div class="card-header background-cyan text-center">
          Ideal shape/resolution: rectangular/1000 x 400
        </div>
        <div class="card-body" align="center"
          style="height: 140px; background-image: url('<%= @meal.image.url if @meal.image.present? %>');
                background-position: center; background-size: cover;">
          <a class="btn btn-secondary box-shadow white" style="margin-top: 30px;">
            <span style="font-size; 20px;">
              <i class="fa fa-camera"></i> Browse
            </span>
          </a>
        </div>
        <div class="card-footer meal-image-name text-center">File name: </div>
      </div>
      <%= f.file_field :image, class:"form-control no-box-shadow height-50 font-15 pf no-display", id: "meal-image-input", label: false %>
    </div>
  </div>
  
  <div class="actions text-center action-button">
    <% if @meal.not_yet_created %>
      <button class="btn btn-primary height-50" id="create_meal" data-disable-with="Saving...">
        Add Ingredients <i class="fa fa-angle-right"></i>
      </button>
    <% else %>
      <%= f.submit "Update", class:"btn btn-primary height-50", id:"create_meal", data: { "disable-with": "Updating..." } %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
  
  $('.meal-image-card').on('click', e => {
    $('#meal-image-input').click();
  });
  
  $('#meal-image-input').on('change', e => {
    $('.meal-image-name').append($('#meal-image-input').get(0).files[0].name);
  });
  
  function showServingTemp() {
    $('.serving-temps').show();
  }
  
  function changeTemp(temp=null) {
    document.querySelector('#serving-temp').value = temp.toLowerCase();
    $('#served').text('served ' + temp);
  }
  
  function changeCourse(course=null) {
    document.querySelector('#course').value = course.toLowerCase();
    $('#course-value').text(course);
  }
  
  function changeFlavor(flavor=null) {
    document.querySelector('#flavor').value = flavor.toLowerCase();
    $('#flavor-value').text(flavor);
  }
    
</script>

app/views/meals/_meal_owner.html.erb
<div class="card">
    <div class="card-header background-cyan">
        Action
    </div>
    
    <div class="card-body">
        <a class="btn btn-primary" href="/meals/<%= @meal.id %>/edit">
            Edit
        </a>
        
        <%= link_to meal_path(@meal), class:"btn btn-danger", method: :delete do %>
            Delete
        <% end %>
    </div>
</div>

app/views/meals/_meals.html.erb
<% if meals.present? %>
    <% meals.each do |m| %>
        <div class="col-md-4 meal-card add-padding-top" style="border-radius: 5px;">
            <a href="/dish/<%= m.id %>/<%= m.slug %>" class="background-transparent theme-blue no-underline">
                <div class="card cursor-pointer no-border">
                    <div class="card-body"
                        style="background-image: url('<%= m.image %>'); background-size: cover;
                            background-position: center; height: 150px; border-radius: 2px;">
                    </div>
                    
                    <div class="meal-card-footer">
                        <span class="font-15 float-left">
                            <%= m.name %>
                        </span>
                        
                        <span class="bold font-13 theme-blue float-right">
                            <span class="badge badge-primary"><%= m.meal_type %></span>
                        </span>
                    </div>
                    <div class="row" style="margin: 0;">
                        <div class="col-lg-12 no-padding">
                            <span class="float-left" style="font-size: 15px !important;">
                                by
                                <a href="/c/<%= m.chef.username %>"
                                    class="theme-cyan font-15" style="margin-left: 5px;">
                                    <%= m.chef.first_name %>
                                </a>
                            </span>
                            
                            <span class="float-right">
                                <span class="cursor-pointer" align="center"
                                    data-toggle="modal" data-target="#rateMeal"
                                    style="margin-left: 10px;">
                                    <% 5.times.each_with_index do |s, idx| %>
                                        <span class="star">
                                            <i class="<%= meal_star_rating(idx + 1, m) %> theme-yellow"
                                                style="font-size: 15px;"></i>
                                        </span>
                                    <% end %>
                                </span>
                            </span>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    <% end %>
<% else %>
    <div class="col-md-12 text-center">
        <img src="/images/not_found.png" height="120">
    </div>
    <div class="col-md-12 text-center text-muted add-margin-top">
        <p>No listings found in your area. Our chefs are actively adding new listings, so check back soon!</p>
    </div>
<% end %>

<script>
    $mealCard = $('.meal-card');
    $mealCard.hover(shadowCard);
    
    function shadowCard() {
        $(this).toggleClass('box-shadow-amp');
    };
</script>

app/views/meals/_no_meal.html.erb
<section id="no-meals-found">
    <div class="row">
        <div class="col-md-12">
            <h5>No meals found</h5>
        </div>
    </div>
</section>

app/views/meals/edit.html.erb
<div>
    <div class="col-lg-10 offset-lg-1 no-padding">
        <div class="dh-card">
            <%= render 'form' %>
        </div>
    </div>
</div>

<div style="margin-top: 15px;">
    <div class="col-lg-10 offset-lg-1 no-padding">
        <div class="dh-card">
            <h5>Ingredients</h5>
            <hr>
            <%= render partial: 'ingredients', locals: { ingredients: @meal.ingredients, meal: @meal } %>
            
            <a href="/listing/<%= @meal.id %>/ingredients"
                class="btn btn-primary mobile-block-display" style="margin-top: 10px;">
                Edit Ingredients
            </a>
        </div>
    </div>
</div>

<div style="margin-top: 20px;">
    <div class="col-lg-10 offset-lg-1 no-padding">
        <div class="dh-card">
            <h5 class="bold">Irreversible Action</h5>
            <hr>
            
            <%= link_to meal_path(@meal), class: "btn btn-danger white mobile-block-display",
                title: "Delete this listing (irreversible action)",
                style:"text-transform: uppercase;", data: {"disable-with": "Deleting..."},
                method: :delete do %>
                Delete This Listing
            <% end %>
            
            <p class="add-margin-top">This action is irreversible!</p>
        </div>
    </div>
</div>

app/views/meals/ingredient_added.js.erb
document.querySelector("#ingredient_form").reset();

$('#ingredients-list').html(`
    <%= render partial: "ingredients", locals: { ingredients: @ingredients, meal: @meal } %>
`);

showNotice("Ingredient Added!");

app/views/meals/new.html.erb
<div class="col-lg-10 offset-lg-1 no-padding">
    <div class="dh-card">
        <h5>Add a new dish</h5>
        <hr>
        <%= render 'form' %>
    </div>
</div>