config/routes.rb
Rails.application.routes.draw do
  
  ## Customer routes
  devise_for :customers, :controllers => { :registrations => "customers/registrations", :sessions => "customers/sessions" }
  devise_scope :customer do
    get 'customer/login', to: 'devise/sessions#new'
    get 'customer/signup', to: 'devise/registrations#new'
    get 'customer/password-settings', to: 'customers/registrations#edit'
    get 'customer/retrieve-password', to: 'devise/passwords#new'
  end
  authenticated :customer do
    root 'customers#index', as: :authenticated_customer_root
  end
  get 'customers/make_reservation', to: 'customers#make_reservation'
  get '/customers/dashboard', to: 'customers#dashboard'
  get '/inbox', to: 'conversations#inbox'
  get '/bookings', to: 'customers#bookings'
  get '/reservation/:id/meals', to: 'customers#reservation_meals'
  get '/edit/profile', to: 'customers#edit'
  get '/customer/edit/profile', to: 'customers#edit'
  get '/featured-listings', to: 'customers#featured_listings'
  get '/:location/listings', to: 'meals#location_based_listings'
  get '/edit/verification', to: 'customers#edit_verification'
  get '/submit_token', to: 'customers#submit_token'
  get '/save_listing/:id', to: 'customers#save_listing'
  get '/wishlist', to: 'customers#wishlist'
  get '/message_chef/:id', to: 'customers#message_chef'
  get '/update_reservation', to: 'reservations#update_reservation'
  ## END CUSTOMER ROUTES ##
  
  ## Chef routes
  devise_for :chefs, :controllers => { :registrations => "chef/registrations" }
  devise_scope :chef do
    get 'chef/login', to: 'devise/sessions#new'
    get 'chef/signup', to: 'devise/registrations#new'
    get 'chef/password-settings', to: 'chef/registrations#edit'
    get 'chef/retrieve-password', to: 'devise/passwords#new'
  end
  authenticated :chef do
    root 'chefs#payout_form', as: :authenticated_chef_root
  end
  get '/chef_onboarding', to: 'chefs#onboarding'
  get '/chef/dashboard', to: 'chefs#dashboard'
  get '/inbox', to: 'conversations#inbox'
  get '/chef/edit/profile', to: 'chefs#edit'
  get '/reservations', to: 'chefs#reservations'
  get '/accept_reservation', to: 'chefs#accept_reservation'
  get '/deny_reservation', to: 'chefs#deny_reservation'
  get '/reservation/:id/:customer_id/accepted', to: 'chefs#accepted'
  get '/reservations/pending', to: 'chefs#pending'
  get '/reservations/accepted', to: 'chefs#all_accepted'
  get '/reservations/denied', to: 'chefs#denied'
  get '/b/:shortened_url', to: 'reservations#book'
  get '/chef/edit/social', to: 'chefs#social_form'
  get '/chef/edit/payout', to: 'chefs#payout_form'
  get '/change_payout', to: 'chefs#change_payout'
  get '/my-requests', to: 'chefs#payout_form'
  get '/chef/edit/listings', to: 'chefs#my_listings'
  get '/verify_bank', to: 'chefs#verify_bank'
  get '/chef/account-created', to: 'chefs#account_created'
  get '/load_reservations', to: 'chefs#load_reservations_category'
  get '/sort_reservations', to: 'chefs#sort_reservations'
  get '/view_request/:id', to: 'chefs#view_request'
  get '/message_diner/:id', to: 'chefs#message_diner'
  post '/rate_diner', to: 'chefs#rate_diner'
  get '/add-ingredients/:id', to: 'meals#ingredients_list', as: 'add_ingredients'
  post "/create_ingredient", to: 'meals#create_ingredient'
  get '/listing/:id/ingredients', to: 'meals#ingredients_list'
  get '/remove_ingredient', to: 'meals#remove_ingredient'
  get '/trigger_payout', to: 'chefs#trigger_payout'
  ## END CHEF ROUTES ##
  
  ## RESOURCES
  resources :conversations, except: [:delete, :edit, :update]
  resources :messages, only: :create
  resources :chefs, :reservations, :customers, :meals
  ## END RESOURCES ##
  
  ## Global routes
  get '/meal/search', to: 'main#search_page'
  get '/search', to: 'main#search'
  get '/new-dish', to: 'meals#new'
  get '/meal/:id/booking-confirmation', to: 'meals#booking_confirmation'
  get '/cook/:id', to: 'chefs#show'
  get '/cook/:username', to: 'chefs#show'
  get '/chef/:username', to: 'chefs#show'
  get '/chat/:id', to: 'conversations#show', as: 'chat'
  get '/dish/:id/:slug', to: 'meals#show', as: 'dish'
  get '/dish/:id/:slug/edit', to: 'meals#edit', as: 'edit_dish'
  get '/new/chat', to: 'conversations#create'
  get '/new/customer/chat', to: 'conversations#contact_customer'
  post '/create_message', to: 'conversations#create_message'
  get '/star/:id', to: 'conversations#star', as: "star_conversation"
  get '/archive/:id', to: 'conversations#archive', as: "archive_conversation"
  get '/unarchive/:id', to: 'conversations#unarchive', as: "unarchive_conversation"
  get '/inbox/archived', to: 'conversations#archived'
  get '/inbox/all', to: 'conversations#all'
  get 'user_type', to: 'main#user_type'
  get '/c/:username', to: 'chefs#show'
  get '/book/:username/:id', to: 'reservations#book', as: 'book'
  get '/start_reservation/:username', to: 'reservations#start_reservation'
  post '/reserve', to: 'reservations#reserve'
  post '/complete-reservation', to: 'reservations#complete_reservation'
  get '/booking-complete', to: 'reservations#booking_complete'
  get '/booking-accepted', to: 'reservations#booking_accepted'
  get '/booking/confirmation/:id', to: 'reservations#booking_confirmation'
  post '/submit_cancellation_request', to: 'reservations#cancel_reservation'
  post '/report-cook', to: 'main#report'
  post '/rate', to: 'main#rate'
  post '/rate_meal', to: 'main#rate_meal'
  get '/booking-estimate', to: 'reservations#booking_estimate'
  get '/search_meal_reviews', to: 'meals#search_meal_reviews'
  get '/browse_reviews', to: 'meals#browse_reviews'
  get '/tagged/:tag', to: 'meals#search_by_tag'
  get '/category/:category', to: 'meals#search_by_category'
  get '/filter_dishes', to: 'meals#filtered_search'
  get '/refer-a-chef', to: 'main#refer_a_chef'
  post '/submit-chef-referral', to: 'main#submit_chef_referral'
  get '/referral', to: 'main#referral'
  get '/verify_referral/:ref', to: 'main#verify_referral'
  get '/join', to: 'main#join'
  get '/new_user_guidelines', to: 'main#new_user_guidelines'
  get '/accept_guidelines', to: 'main#accept_guidelines'
  get '/terms', to: 'main#terms'
  get '/contact-us', to: "main#contact"
  ## END GLOBAL ROUTES ##
  
  
  
  root 'main#home'
end

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top main-navbar">
    <div class="container">
        <a class="navbar-brand cursor-pointer" href="/blog" style="color: inherit;">
            <img src="https://s3.us-east-2.amazonaws.com/senzzu/logo-transparent.png" alt="Senzzu" height="47"> | <span class="bold">Blog</span>
        </a>
        <button class="navbar-toggler btn btn-primary btn-nav nav-link white" onclick="window.location.href='/'">
            Home
        </button>
        
        <div class="collapse navbar-collapse justify-content-end" id="navbarMobile">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <div class="dropdown">
                        <a class="btn btn-primary nav-link white" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span id="storeName"><%= current_admin.name %></span> <i class="fa fa-angle-down"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item category cursor-pointer"
                                href="/admin/edit/profile">
                                Profile settings
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item category cursor-pointer"
                                href="/admin/posts">
                                Posts written
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item category cursor-pointer"
                                href="/blog/new">
                                New post
                            </a>
                            <div class="dropdown-divider"></div>
                            <%= link_to destroy_admin_session_path, class:"dropdown-item category cursor-pointer", method: :delete do %>
                                Sign out
                            <% end %>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_blog_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top main-navbar">
    <div class="container">
        <a class="navbar-brand cursor-pointer" href="/blog" style="color: inherit;">
            <img src="https://s3.us-east-2.amazonaws.com/senzzu/logo-transparent.png" alt="Senzzu" height="47"> | <span class="bold">Blog</span>
        </a>
        <button class="navbar-toggler btn btn-primary btn-nav nav-link white" onclick="window.location.href='/'">
            Home
        </button>
        
        <div class="collapse navbar-collapse justify-content-end" id="navbarMobile">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="btn btn-primary btn-nav nav-link white box-shadow" href="/blog/admin/login">
                        Admin login
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_chef_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top chef-navbar">
    <!--<div class="container" style="height: 100% !important;">-->
        <a class="navbar-brand cursor-pointer" href="/"><img src="/images/logo-transparent.png" height="50"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation"
        onclick="$('.dh-navbar-collapse').toggleClass('display-block'); $('.navbar').toggleClass('background-white');">
            <span class="navbar-toggler-icon">
                <i class="fa fa-bars"></i>
            </span>
        </button>
        
        <%= render "layouts/mobile_dropdown" %>
        
        <div class="collapse navbar-collapse justify-content-start no-mobile-display" style="height: 100%;">
            <ul class="navbar-nav" style="height: 100%;">
                <li class="nav-item">
                    <span class="nav-link-child">
                        <%= render 'common/search_form' %>
                    </span>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse justify-content-end no-mobile-display" id="navbarSupportedContent" style="height: 100%;">
            <ul class="navbar-nav" style="height: 100%;">
                <li class="nav-item nav-item-nav">
                    <a class="nav-link-child background-transparent no-underline" href="/new-dish">
                        <button class="btn btn-link nav-link" style="height: 100%;">
                            Add a dish
                        </button>
                    </a>
                </li>
                <li class="nav-item nav-item-nav">
                    <a class="nav-link-child background-transparent no-underline" href="/reservations">
                        <button class="btn btn-link nav-link" style="height: 100%;">
                            Reservations
                            <% if pending_reservations %>
                                <span class="badge badge-success">
                                    <%= pending_reservations_count %> new requests
                                </span>
                            <% end %>
                        </button>
                    </a>
                </li>
                <li class="nav-item nav-item-nav">
                    <a class="nav-link-child background-transparent no-underline" href="/inbox">
                        <button class="btn btn-link nav-link" style="height: 100%;">
                            Messages <i class="<%= inbox_status %>" style="font-size: 8px; vertical-align: super !important;"></i>
                        </button>
                    </a>
                </li>
                <li class="nav-item nav-item-nav" style="height: 100%;">
                    <div class="dropdown" style="height: 100%;">
                        <div id="cook-avi" align="center" class="cursor-pointer"
                            style="height: 35px; width: 35px; margin: auto;
                                    overflow: hidden; border-radius: 17.5px;
                                    border: 0.5px solid #e7e7e9; margin-top: 20px;"
                            id="dropdownMenuButton" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <img src="<%= current_chef.image.url %>" alt="cook"
                                style="height: auto; width: inherit;">
                        </div>
                        <div class="dropdown-menu box-shadow no-border-radius dropdown-menu-right"
                            aria-labelledby="dropdownMenuButton"
                            style="border-color: #eee; padding: 0; margin-top: -18.5px;
                                width: 250px;">
                            <a class="background-transparent dropdown-item cursor-pointer"
                                href="/chef/edit/profile">
                                Account Settings
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="background-transparent dropdown-item cursor-pointer"
                                href="/chef/password-settings">
                                Password Settings
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="background-transparent dropdown-item cursor-pointer"
                                href="/chef/edit/payout">
                                Payout Settings
                                <% if current_chef.payout_settings_incomplete %>
                                    <span class="badge badge-warning">
                                        incomplete
                                    </span>
                                <% end %>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="background-transparent dropdown-item cursor-pointer"
                                href="/chef/edit/listings">
                                My Listings
                            </a>
                            <div class="dropdown-divider"></div>
                            <%= link_to destroy_chef_session_path, class:"background-transparent dropdown-item", method: :delete do %>
                                Log Out
                            <% end %>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    <!--</div>-->
</nav>

<script type="text/javascript">
    $('#request-location').click(function() {
        $('#request-location')
        .css({'width': '430px'})
        .toggleClass('no-bottom-radii');
        $('.input-group-text')
        .toggleClass('no-bottom-radii');
        $('#search-box').fadeIn();
    });
    
    $('#request-location').focusout(function() {
        $('#request-location')
        .toggleClass('no-bottom-radii');
        
        $('.input-group-text')
        .toggleClass('no-bottom-radii');
    });
</script>

app/views/layouts/_customer_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top">
    <!--<div class="container" style="height: 100% !important;">-->
        <a class="navbar-brand cursor-pointer" href="/"><img src="/images/logo-transparent.png" height="50"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation"
        onclick="$('.dh-navbar-collapse').toggleClass('display-block'); $('.navbar').toggleClass('background-white');">
            <span class="navbar-toggler-icon">
                <i class="fa fa-bars font-blue" style="font-size: 30px !important;"></i>
            </span>
        </button>
        
        <%= render "layouts/mobile_dropdown" %>
        
        <div class="collapse navbar-collapse justify-content-start no-mobile-display" style="height: 100%;">
            <ul class="navbar-nav" style="height: 100%;">
                <li class="nav-item">
                    <span class="nav-link-child">
                        <%= render 'common/search_form' %>
                    </span>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse justify-content-end no-mobile-display" id="navbarSupportedContent" style="height: 100%;">
            <ul class="navbar-nav" style="height: 100%;">
                <li class="nav-item nav-item-nav">
                    <a class="nav-link-child background-transparent no-underline" href="/wishlist">
                        <button class="btn btn-link nav-link" style="height: 100%;">
                            Saved
                        </button>
                    </a>
                </li>
                <li class="nav-item nav-item-nav">
                    <a class="nav-link-child background-transparent no-underline" href="/bookings">
                        <button class="btn btn-link nav-link" style="height: 100%;">
                            Bookings
                        </button>
                    </a>
                </li>
                <li class="nav-item nav-item-nav">
                    <a class="nav-link-child background-transparent no-underline" href="/inbox">
                        <button class="btn btn-link nav-link" style="height: 100%;">
                            Messages <i class="<%= inbox_status %>" style="font-size: 8px; vertical-align: super !important;"></i>
                        </button>
                    </a>
                </li>
                <li class="nav-item nav-item-nav" style="height: 100%;">
                    <div class="dropdown" style="height: 100%;">
                        <div id="customer-avi" align="center" class="cursor-pointer"
                            style="height: 35px; width: 35px; margin: auto;
                                    overflow: hidden; border-radius: 17.5px;
                                    border: 0.5px solid #e7e7e9; margin-top: 20px;"
                            id="dropdownMenuButton" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <img src="<%= current_customer.image %>" alt="cook"
                                style="height: auto; width: inherit;">
                        </div>
                        <div class="dropdown-menu box-shadow no-border-radius dropdown-menu-right"
                            aria-labelledby="dropdownMenuButton"
                            style="border-color: #eee; padding: 0; margin-top: -18.5px;
                                width: 250px;">
                            <a class="background-transparent dropdown-item cursor-pointer"
                                href="/edit/profile">
                                Edit profile
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="background-transparent dropdown-item cursor-pointer"
                                href="/customer/password-settings">
                                Password Settings
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="background-transparent dropdown-item cursor-pointer"
                                href="/edit/verification">
                                Verification
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="background-transparent dropdown-item cursor-pointer"
                                href="/refer-a-chef">
                                Refer chefs
                            </a>
                            <div class="dropdown-divider"></div>
                            <%= link_to destroy_customer_session_path, class:"background-transparent dropdown-item", method: :delete do %>
                                Sign out
                            <% end %>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    <!--</div>-->
</nav>

<script type="text/javascript">
    $('#request-location').click(function() {
        $('#request-location')
        .css({'width': '430px'})
        .toggleClass('no-bottom-radii');
        $('.input-group-text')
        .toggleClass('no-bottom-radii');
        $('#search-box').fadeIn();
    });
    
    $('#request-location').focusout(function() {
        $('#request-location')
        .toggleClass('no-bottom-radii');
        
        $('.input-group-text')
        .toggleClass('no-bottom-radii');
    });
</script>

app/views/layouts/_main_body.erb
<section id="main-body">
    <%= yield %>
</section>

app/views/layouts/_main_body.html.erb
<section id="main-body" class="container" style="height: 100% !important;">
    <div class="modal fade" id="customerAuthentication" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="z-index: 1051 !important;">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="authenticationModal">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true" style="font-size: 30px;">
                            &times;
                        </span>
                    </button>
                </div>
                <div class="modal-body" id="authenticationModalBody">
                    <div class="modal-body-header">
                        <h4 class="bold modal-body-header-headline add-margin-bottom"
                            align="center">
                            Log In
                        </h4>
                    </div>
                    
                    <%= form_for @customer, url: "/customers/sign_in", id: "new_customer", method: :post do |f| %>
                        <div class="form-inputs" style="vertical-align: middle !important;">
                          
                          <div class="field">
                            <%= f.email_field :email, required: true, class:"form-control height-50 no-box-shadow", autofocus: true, placeholder:"Email", input_html: { autocomplete: 'email' } %>
                          </div>
                        
                          <div class="field">
                            <%= f.password_field :password, required: false, class:"form-control height-50 no-box-shadow", input_html: { autocomplete: "current-password" }, placeholder:"Password" %>
                          </div>
                        
                          <div class="actions" style="margin-top: 10px;">
                            <div class="row">
                              <div class="col-md-12">
                                <%= f.submit "Log in", class:"btn btn-primary btn-block height-50 log-in no-box-shadow", id:"logIn", data: {"disable-with": "Logging you in..."} %>
                              </div>
                              <div class="col-md-12 add-padding-top text-center">
                                  <%= link_to "Don't have an account? Register here", customer_signup_path, class:"background-transparent theme-blue font-16 display-block" unless request.original_url.include?('chef') %>
                                  <%= link_to "Forgot your password?", customer_retrieve_password_path, class:"background-transparent theme-blue font-16 display-block" unless request.original_url.include?('chef') %>
                              </div>
                            </div>
                          </div>
                          
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <%= yield %>
</section>

app/views/layouts/_mobile_dropdown.html.erb
<% if current_chef %>
    <div class="dh-navbar-collapse box-shadow display-mobile">
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/new-dish" style="color: #000;">
                <i class="fa fa-plus-circle"></i> Add a dish
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/reservations" style="color: #000;">
                <i class="fa fa-calendar"></i> Reservations
                <% if pending_reservations %>
                    <span class="badge badge-success">
                        <%= pending_reservations_count %> new requests
                    </span>
                <% end %>
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/inbox" style="color: #000;">
                <i class="fa fa-envelope-o"></i> Messages <i class="<%= inbox_status %>" style="font-size: 8px; vertical-align: super !important;"></i>
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/chef/edit/profile" style="color: #000;">
                <i class="fa fa-user-circle"></i> Account Settings
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/chef/edit/payout" style="color: #000;">
                <i class="fa fa-credit-card"></i> Payout Settings
                <% if current_chef.payout_settings_incomplete %>
                    <span class="badge badge-warning">
                        incomplete
                    </span>
                <% end %>
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/chef/password-settings" style="color: #000;">
                <i class="fa fa-lock"></i> Password Settings
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/chef/edit/listings" style="color: #000;">
                <i class="fa fa-file-text-o"></i> My Listings
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <%= link_to destroy_chef_session_path, class:"background-transparent",
                style:"color: #000;", method: :delete do %>
                <i class="fa fa-sign-out"></i> Log Out
            <% end %>
        </div>
    </div>
<% elsif current_customer %>
    <div class="dh-navbar-collapse box-shadow display-mobile">
        <div class="dh-navbar-collapse-nav">
            <div id="pac-container" style="width: 100%;">
                <form action="/search" method="get" id="banner-search-form">
                    <div class="input-group mb-3"
                        style="margin-bottom: 0 !important; border-radius: 0; border: none;">
                        <input class="form-control" name="request_location"
                            id="banner-request-location" autocomplete="off"
                            placeholder="Search listings..." type="search"
                            style="height: 70px; font-size: 16px;
                                width: 50%; border-radius: 0; border: none;
                                box-shadow: none !important;" required="true"
                                onkeyup="adjustPacContainerWidth()">
                    </div>
                    <button class="no-display">Submit</button>
                </form>
                <div id="map" style="display: none;"></div>
                <div id="infowindow-content">
                </div>
            </div>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/wishlist" style="color: #000;">
                <i class="fa fa-bookmark"></i> Saved
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/bookings" style="color: #000;">
                <i class="fa fa-calendar"></i> Bookings
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/inbox" style="color: #000;">
                <i class="fa fa-envelope-o"></i> Messages <i class="<%= inbox_status %>" style="font-size: 8px; vertical-align: super !important;"></i>
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/edit/profile" style="color: #000;">
                <i class="fa fa-user-circle"></i> Account Settings
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/customer/password-settings" style="color: #000;">
                <i class="fa fa-lock"></i> Password Settings
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/edit/verification" style="color: #000;">
                <i class="fa fa-shield"></i> Verification
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" href="/refer-a-chef" style="color: #000;">
                <i class="fa fa-share-square-o"></i> Refer Chefs
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <%= link_to destroy_customer_session_path, class:"background-transparent", method: :delete do %>
                <i class="fa fa-sign-out"></i> Sign out
            <% end %>
        </div>
    </div>
<% else %>
    <div class="dh-navbar-collapse box-shadow display-mobile">
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" data-toggle="modal"
                data-target="#customerAuthentication" style="color: #000;">
                Diner Login
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent" style="color: #000;" href="/chef/login">
                Cook Login
            </a>
        </div>
        <div class="dh-navbar-collapse-nav">
            <a class="background-transparent font-blue bold" href="/join">
                Join DinnerHost
            </a>
        </div>
    </div>
<% end %>

app/views/layouts/index.html.erb
<section id="banner" style="height: 650px; margin-top: -200px; background-image: url('/images/principal_banner.jpg'); background-size: cover; background-position: center;">
    
</section>